import { Deck } from "./definitions";

export const decks: Deck[] = [
  {
    id: "d1",
    name: "Allgemeinwissen",
    description: "Grundlegende Fragen aus verschiedenen Bereichen",
    tags: ["bildung", "quiz"],
    cardIds: ["c1", "c2"],
    color: "#ffcc00",
    icon: "📚",
    totalCards: 2,
    newCards: 1,
    learningCards: 1,
    reviewCards: 0,
    dueToday: 1,
    studiedToday: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    revision: 1,
  },
  {
    id: "d2",
    name: "Bilder & Objekte",
    description: "Visuelles Lernen mit Bildern",
    tags: ["bilder", "lernen"],
    cardIds: ["c3", "c4"],
    color: "#00ccff",
    icon: "🖼️",
    totalCards: 2,
    newCards: 0,
    learningCards: 1,
    reviewCards: 1,
    dueToday: 1,
    studiedToday: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    revision: 1,
  },
  {
    id: "d3",
    name: "Astronomie",
    tags: ["weltall", "sterne"],
    cardIds: ["c4"],
    color: "#663399",
    icon: "🌌",
    parentDeckId: "d2",
    totalCards: 1,
    newCards: 0,
    learningCards: 0,
    reviewCards: 1,
    dueToday: 1,
    studiedToday: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    revision: 1,
  },
];