import { Card } from "./definitions";

const cards: Card[] = [
  {
    id: "c1",
    deckId: ["d1"],
    front: "Was ist die Hauptstadt von Frankreich?",
    back: "Paris",
    hint: "Es ist auch die Stadt der Liebe",
    extra: "Wird oft als touristisches Highlight genannt",
    tags: ["geografie", "europa"],
    media: [],
    state: "new",
    due: new Date(),
    rating: 0,
    totalReviews: 0,
    correctReviews: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    revision: 1,
  },
  {
    id: "c2",
    deckId: ["d1"],
    front: "Nenne das chemische Symbol von Wasserstoff",
    back: "H",
    tags: ["chemie", "elemente"],
    media: [],
    state: "learning",
    due: new Date(Date.now() + 1000 * 60 * 60 * 24), // morgen
    rating: 2,
    totalReviews: 3,
    correctReviews: 2,
    lastReview: new Date(Date.now() - 1000 * 60 * 60 * 24),
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    revision: 2,
  },
  {
    id: "c3",
    deckId: ["d2"],
    front: "Zeige das Bild eines Apfels",
    back: "Das ist ein Apfel",
    tags: ["lebensmittel", "bilder"],
    media: [
      { id: "m1", type: "image", url: "https://example.com/apple.jpg" },
    ],
    state: "review",
    due: new Date(Date.now() - 1000 * 60 * 60), // vor einer Stunde
    rating: 3,
    totalReviews: 5,
    correctReviews: 5,
    lastReview: new Date(Date.now() - 1000 * 60 * 60),
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    revision: 3,
  },
  {
    id: "c4",
    deckId: ["d2", "d3"],
    front: "Wie viele Planeten hat unser Sonnensystem?",
    back: "8",
    hint: "Früher galt Pluto als 9.",
    tags: ["astronomie"],
    media: [],
    state: "suspended",
    due: new Date(),
    rating: 1,
    totalReviews: 4,
    correctReviews: 2,
    lastReview: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    deleted: false,
    revision: 1,
  },
];


