name: Build Backend

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/build-backend.yml"
      - ".github/workflows/deploy-backend.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run build
